### ISSUE TITLE
What about the performance of this reproduction?

### ISSUE THREAD

**Issue by Wuziyi616** [lyqun/PU-Net_pytorch#1]
Hi! Thank you for your great work! Recently I'm also trying to reproduce PU-Net in pytorch and came across your repo. I just wonder what performance did you get using this repo? Is it competitive with the original paper? Thanks!

**Comment by lyqun** [comment]
In this repo, results of the baseline model are (NUC) 0.2396 0.1992 0.1764 0.1620 0.1536 0.1482 with different p (0.2% 0.4% 0.6% 0.8% 1.0% 1.2%, respectively). The official results are 0.174 0.138 0.122 0.115 0.112 0.110. For NUC, the lower is better. Note that we evaluated the NUC only on 40 disks (9000 in the paper, section 4.3) since it took us a very long time. For full evaluation, please refer to this issue https://github.com/yulequan/PU-Net/issues/14.

Furthermore, we also provide the EMD and CD evaluated on test split (on patches, not on complete objects).
EMD: 0.110 * 10^2
CD: 0.305 * 10^3

I will update the README later.

**Comment by Wuziyi616** [comment]
Thank you so much for your quick reply! BTW, would you mind uploading the weight for the model you trained which gets the result you mentioned? It will be helpful because I won't need to download the training data and train it by myself (I just want to use a pre-trained PU-Net for other applications). Thanks!

**Comment by lyqun** [comment]
Model weight for the baseline model is uploaded to [Google Drive](https://drive.google.com/file/d/18CJGHgc-BM8pLbA23vIX0VdWvdmsaS6q/view?usp=sharing). Please feel free to contact me if you encounter any problem.

**Comment by Wuziyi616** [comment]
Got it! Thank you so much for your help!

**Comment by 3330897832** [comment]
$ python eval.py --gpu 0 --resume logs/punet_baseline/punet_epoch_99.pth
Namespace(batch_size=8, gpu=0, model='punet', resume='logs/punet_baseline/punet_epoch_99.pth', up_ratio=4, use_bn=False, use_res=False, workers=4)
Traceback (most recent call last):
  File "eval.py", line 24, in <module>
    from chamfer_distance import chamfer_distance
  File "E:\zhuomian\PU-Net\PU-Net\chamfer_distance\__init__.py", line 1, in <module>
    from .chamfer_distance import chamfer_distance
  File "E:\zhuomian\PU-Net\PU-Net\chamfer_distance\chamfer_distance.py", line 11, in <module>
    cd = load(name="cd", sources=sources)
  File "F:\Anaconda\envs\da_chuang\lib\site-packages\torch\utils\cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "F:\Anaconda\envs\da_chuang\lib\site-packages\torch\utils\cpp_extension.py", line 1317, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "F:\Anaconda\envs\da_chuang\lib\site-packages\torch\utils\cpp_extension.py", line 1699, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "F:\Anaconda\envs\da_chuang\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'cd'

I'd be appreciated if you can help me solve this problem! Thanks !
